language: c

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install flex libconfig9 libconfig-dev

compiler:
   - gcc
   - clang

script:
   - ./bootstrap.sh
   - ./configure
   - make
   - sudo make install

# todo: test
