language: c

branches:
   only:
      - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install flex

compiler:
   - gcc
   - clang

script:
   - ./bootstrap.sh
   - ./configure
   - make
   - sudo make install

# todo: test
