/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef IEEE8021BRIDGEBASETABLE_H
#define IEEE8021BRIDGEBASETABLE_H

/* function declarations */
void init_ieee8021BridgeBaseTable(void);
void initialize_table_ieee8021BridgeBaseTable(void);
Netsnmp_Node_Handler ieee8021BridgeBaseTable_handler;

/* column number definitions for table ieee8021BridgeBaseTable */
	#define COLUMN_IEEE8021BRIDGEBASECOMPONENTID             1
	#define COLUMN_IEEE8021BRIDGEBASEBRIDGEADDRESS           2
	#define COLUMN_IEEE8021BRIDGEBASENUMPORTS                3
	#define COLUMN_IEEE8021BRIDGEBASECOMPONENTTYPE           4
	#define COLUMN_IEEE8021BRIDGEBASEDEVICECAPABILITIES      5
	#define COLUMN_IEEE8021BRIDGEBASETRAFFICCLASSESENABLED   6
	#define COLUMN_IEEE8021BRIDGEBASEMMRPENABLEDSTATUS       7
	#define COLUMN_IEEE8021BRIDGEBASEROWSTATUS               8
#endif /* IEEE8021BRIDGEBASETABLE_H */

/* Typical data structure for a row entry */
struct ieee8021BridgeBaseTable_entry {
	/* Index values */
	u_long ieee8021BridgeBaseComponentId;

	/* Column values */
	char ieee8021BridgeBaseBridgeAddress[16];
	size_t ieee8021BridgeBaseBridgeAddress_len;
	char old_ieee8021BridgeBaseBridgeAddress[16];
	size_t old_ieee8021BridgeBaseBridgeAddress_len;
	long ieee8021BridgeBaseNumPorts;
	long ieee8021BridgeBaseComponentType;
	long old_ieee8021BridgeBaseComponentType;
	char ieee8021BridgeBaseDeviceCapabilities[8];
	size_t ieee8021BridgeBaseDeviceCapabilities_len;
	char old_ieee8021BridgeBaseDeviceCapabilities[8];
	size_t old_ieee8021BridgeBaseDeviceCapabilities_len;
	long ieee8021BridgeBaseTrafficClassesEnabled;
	long old_ieee8021BridgeBaseTrafficClassesEnabled;
	long ieee8021BridgeBaseMmrpEnabledStatus;
	long old_ieee8021BridgeBaseMmrpEnabledStatus;
	long ieee8021BridgeBaseRowStatus;

	int   valid;
};
