/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef IEEE8021BRIDGEEVBSYS_H
#define IEEE8021BRIDGEEVBSYS_H

/* function declarations */
void init_ieee8021BridgeEvbSys(void);
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysType;
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysNumExternalPorts;
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysEvbLldpTxEnable;
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysEvbLldpManual;
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysEvbLldpGidCapable;
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysEcpAckTimer;
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysEcpMaxRetries;
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysVdpDfltRsrcWaitDelay;
Netsnmp_Node_Handler handle_ieee8021BridgeEvbSysVdpDfltReinitKeepAlive;

#endif /* IEEE8021BRIDGEEVBSYS_H */
